
all:
	cd libs && make -j4
	cd network_train && make -j4
	cd predict_trajectory && make -j4
	cd basis_train && make -j4


clean:
	cd libs && make clean
	cd network_train && make clean
	cd predict_trajectory && make clean
	cd basis_train && make clean
